### ISSUE TITLE
Create failing tests for sprint 1

### ISSUE THREAD

**Issue by ingridstoleru** [fii-uaic/SemEval-2019#15]
## Preprocessing:
- [x] Eliminate stop words (of, the, in ...)
- [x] Tokenization
- [x] Replace all negation words with "not"

## Feature extraction: 
- [x] Identify number of capitalized words
- [x] Identify number of elongated words
- [x] Identify number of negation words

## Feature selection:
- [x] Use all features

## Model:
- [x] MLP (Multilayer Perceptron Model)

**Comment by simi2525** [comment]
We did it folks!
